# Generated by Django 2.1.7 on 2022-06-28 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('emailid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('bookingdate', models.DateField(blank=True, null=True)),
                ('deliverytype', models.CharField(blank=True, max_length=20, null=True)),
                ('deliverydate', models.DateField(blank=True, null=True)),
                ('advancepaid', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('colorid', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('imageback', models.CharField(blank=True, max_length=50, null=True)),
                ('imageside', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colors',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customercode', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('emailid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('bookingid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('chassisnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('service1', models.DateField(blank=True, null=True)),
                ('service2', models.DateField(blank=True, null=True)),
                ('service3', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EVModel',
            fields=[
                ('modelid', models.AutoField(primary_key=True, serialize=False)),
                ('gear', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension', models.CharField(blank=True, max_length=50, null=True)),
                ('batterycapacity', models.CharField(blank=True, max_length=50, null=True)),
                ('wheel', models.CharField(blank=True, max_length=50, null=True)),
                ('brake', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('emission', models.CharField(blank=True, max_length=50, null=True)),
                ('usb', models.CharField(blank=True, max_length=50, null=True)),
                ('chargingtime', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'evmodel',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('amountpaid', models.IntegerField(blank=True, null=True)),
                ('paiddate', models.DateField(blank=True, null=True)),
                ('transactionid', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('bookingid', models.ForeignKey(blank=True, db_column='bookingid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evapp.Booking')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotationnumber', models.AutoField(primary_key=True, serialize=False)),
                ('quotationdate', models.DateField(blank=True, null=True)),
                ('availfinance', models.CharField(blank=True, max_length=3, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('totalamount', models.IntegerField(blank=True, null=True)),
                ('colorid', models.ForeignKey(blank=True, db_column='colorid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evapp.Colors')),
                ('customercode', models.ForeignKey(blank=True, db_column='customercode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evapp.Customer')),
            ],
            options={
                'db_table': 'quotation',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('modelname', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': True,
            },
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='evmodel',
            name='modelname',
            field=models.ForeignKey(blank=True, db_column='modelname', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='colors',
            name='modelid',
            field=models.ForeignKey(blank=True, db_column='modelid', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evapp.EVModel'),
        ),
        migrations.AddField(
            model_name='colors',
            name='modelname',
            field=models.ForeignKey(blank=True, db_column='modelname', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quotationnumber',
            field=models.ForeignKey(blank=True, db_column='quoatationnumber', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evapp.Quotation'),
        ),
    ]
