# Generated by Django 2.1.7 on 2022-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
