# Generated by Django 2.1.7 on 2022-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0002_auto_20220702_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
