# Generated by Django 2.1.7 on 2022-07-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0003_auto_20220707_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
        migrations.AlterField(
            model_name='booking',
            name='advancepaid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amountpaid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='totalamount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
