# Generated by Django 2.1.7 on 2022-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0004_auto_20220707_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, default='New', max_length=20, null=True),
        ),
    ]
